- hosts: localhost
  become: true
  pre_tasks: 
    - name: Update Cache
      pacman: 
        update_cache: true
      tags: 
      - node 
      - zsh
      - tools
      - dotfiles
      - ssh
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "/home/caleb/.ssh/id_ed25519"
    # pub_source_key: "./.ssh/id_ed25519.pub"
    # pub_dest_key: "/home/caleb/.ssh/id_ed25519.pub"
  tasks: 
  # - include_tasks: tasks/zsh.yml
  # - include_tasks: tasks/node.yml
  # - include_tasks: tasks/tools.yml
  - include_tasks: tasks/ssh.yml
  - include_tasks: tasks/dotfiles.yml

