- name: Install stow
  pacman:
    name: stow
- name: JetBrains
  pacman: 
    name: ttf-jetbrains-mono-nerd
- name: Cloning dotfiles
  become: yes
  become_user: "{{lookup('env', 'USER')}}"
  ansible.builtin.git:
    repo: 'git@github.com:ctheil/dotfiles.git'
    dest: "~/dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: arch
  tags:
    - dotfiles
- name: Stow dotfiles
  become: yes
  become_user: "{{lookup('env', 'USER')}}"
  shell: cd ~/dotfiles && stow .
  tags:
    - dotfiles
