- name: Install openssh
  pacman: 
    name: openssh
  tags: ssh
- name: Ensure .ssh directory exists.
  become: yes
  become_user: "{{lookup('env', 'USER')}}"
  file:
    dest: "{{ dest_key | dirname }}"
    mode: 0700
    state: directory
  tags:
    - dotfiles
    - ssh
- name: Install ssh key
  become: yes
  become_user: "{{lookup('env', 'USER')}}"
  copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: 0600
  tags:
    - dotfiles
    - ssh
- name: Install pub ssh key
  become: yes
  become_user: "{{lookup('env', 'USER')}}"
  copy:
    src: "{{ source_key }}.pub"
    dest: "{{ dest_key }}.pub"
    mode: 0644
  tags:
    - dotfiles
    - ssh
- name: Set authorized key took from file
  authorized_key:
    user: "{{lookup('env', 'USER')}}"
    state: present
    key: "{{lookup('file', '~/.ssh/id_ed25519.pub')}}"
  # with_fileglob:
  # - "{{lookup('env', 'HOME')}}/.ssh/*.pub"
  tags:
    - dotfiles
    - ssh
- name: add github to known hosts
  ansible.builtin.known_hosts:
    path: "/etc/ssh/ssh_known_hosts"
    name: "github.com"
    key: "{{lookup('pipe', 'ssh-keyscan -t rsa github.com')}}"
    state: present
  tags:
    - dotfiles
    - ssh

