- name: Install openssh
  pacman: 
    name: openssh
  tags: ssh
- name: Ensure .ssh directory exists.
  become_user: root
  file:
    dest: "{{ dest_key | dirname }}"
    mode: 0700
    state: directory
  tags:
    - dotfiles
    - ssh
- name: Install ssh key
  become_user: root
  copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: 0600
  tags:
    - dotfiles
    - ssh
- name: Install pub ssh key
  become_user: root
  copy:
    src: "{{ pub_source_key }}"
    dest: "{{ pub_dest_key }}"
    mode: 0600
  tags:
    - dotfiles
    - ssh
- name: Append ssh public key to authorized_keys via shell
  become_user: root
  shell: |
    cat /home/caleb/.ssh/id_ed25519.pub >> /home/caleb/.ssh/authorized_keys
  args: 
    executable: /bin/bash
  tags:
    - dotfiles
    - ssh
# - name: Debug file lookup
#   become_user: root
#   shell: cat /home/caleb/.ssh/id_ed25519.pub
#   register: command_output
# - name: Print to console
#   become_user: root
#   debug: 
#     msg: "{{command_output.stdout}}"
# - name: Debug lookup
#   become_user: root
#   debug: 
#     msg: "{{ lookup('file', '/home/caleb/.ssh/id_ed25519.pub')}}"


# - name: Set authorized key took from file
#   become_user: root
#   authorized_key:
#     user: caleb
#     state: present
#     key: "{{ lookup('file', '/home/caleb/.ssh/id_ed25519.pub')}}"
#     # key: "/home/caleb/.ssh/id_ed25519.pub"
#   tags:
#     - dotfiles
#     - ssh
