- name: Install BAT
  pacman: 
    name: bat
  tags:
  - tools
- name: Install zoxide
  pacman:
    name: zoxide
  tags:
  - tools
- name: Install TPM
  shell: git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
  tags: 
  - tools
- name: Install tmux
  pacman:
    name: tmux
  tags:
  - tools
# - name: Install Kitty
#   pacman: 
#     name: kitty
#   tags:
#   - tools
- name: install fzf
  pacman: 
    name: fzf
  tags:
  - tools
- name: install exa
  pacman: 
    name: eza
  tags:
  - tools
- name: install ripgrep
  pacman: 
    name: ripgrep
  tags:
  - tools
- name: install firefox
  pacman: 
    name: firefox
  tags:
  - tools
- name: Rustup
  pacman: 
    name: rustup
# alacritty depends on rustup
- name: cargo
  shell: rustup default stable
- name: Install Alacritty Deps
  pacman: 
    name: 
      - cmake 
      - freetype2 
      - fontconfig 
      - pkg-config 
      - make 
      - libxcb 
      - libxkbcommon 
      - python
  tags:
    - tools
- name: Install and build alacritty
  shell: git clone https://github.com/alacritty/alacritty.git && cd alacritty && cargo build --release
- name: Alacritty Desktop Entity
  shell: sudo cp target/release/alacritty /usr/local/bin && sudo cp extra/logo/alacritty-term.svg /usr/share/pixmaps/Alacritty.svg && sudo desktop-file-install extra/linux/Alacritty.desktop && sudo update-desktop-database
- name: Install p10k
  become: true
  become_user: "{{lookup('env', 'USER')}}"
  ansible.builtin.git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: ~/powerlevel10k
    depth: 1
# - name: Install JetBrains font
#   become: true
#   become_user: "{{lookup('env', 'USER')}}"
#   ansible.builtin.get_url:
#     url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/JetBrainsMono.zip 
#     dest: ~/.local/share/fonts

