- name: Install Git
  pacman:
    name: git
  tags: 
  - zsh
- name: Install Zsh
  pacman:
    name: zsh
  tags: 
  - zsh
- name: Install oh-my-zsh
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: ~/
  tags: 
  - zsh
- name: Install zsh-autosuggestions
  ansible.builtin.git: 
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags: 
  - zsh
- name: Install zsh-syntax-highlighting
  ansible.builtin.git: 
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "~/.oh-my-zsh/plugins/zsh-syntax-highlighting"
  tags: 
  - zsh
- name: Update .zshrc
  shell: sed -i 's/(git/(git zsh-autosuggestions zsh-syntax-highlighting vi-mode/' ~/.zshrc
  tags: 
  - zsh
