- name: Install Git
  pacman:
    name: git
  tags: 
  - zsh
- name: Install Zsh
  pacman:
    name: zsh
  tags: 
  - zsh
- name: Install oh-my-zsh
  become: true
  become_user: "{{lookup('env', 'USER')}}"
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  tags: 
  - zsh
- name: Install zsh-autosuggestions
  become: true
  become_user: "{{lookup('env', 'USER')}}"
  ansible.builtin.git: 
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags: 
  - zsh
- name: Install zsh-syntax-highlighting
  become: true
  become_user: "{{lookup('env', 'USER')}}"
  ansible.builtin.git: 
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "~/.oh-my-zsh/plugins/zsh-syntax-highlighting"
  tags: 
  - zsh
- name: remove default .zshrc
  become: true
  become_user: "{{lookup('env', 'USER')}}"
  shell: mv ~/.zshrc ~/.zshrc.bak

# - name: Update .zshrc
#   become: true
#   become_user: "{{lookup('env', 'USER')}}"
#   shell: sed -i 's/(git/(git zsh-autosuggestions zsh-syntax-highlighting vi-mode/' ~/.zshrc
#   tags: 
#   - zsh
